### ISSUE TITLE
manifest.json version not updated

### ISSUE THREAD

**Issue by hmmbob** [jeatheak/Mitsubishi-WF-RAC-Integration#100]
The manifest is running few releases behind:

https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/main/custom_components/mitsubishi_wf_rac/manifest.json#L10

Which results in:
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/33529490/d415a548-93f0-47f9-99e7-4a574256829c)

while this is the real version installed:
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/33529490/7cf565a0-e27d-4bc5-b868-dd84e1b021c5)

**Comment by jeatheak** [comment]
merged in release 2024.6
