### ISSUE TITLE
Horizontal select missing

### ISSUE THREAD

**Issue by Leecavturbo** [jeatheak/Mitsubishi-WF-RAC-Integration#101]
We need 4 radio buttons not 3.
Mode, Fan, Vertical, Horizontal.

![IMG_7397](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/116071327/ec3c83e6-4d16-498f-a4d7-3e2dddbbad66)

**Comment by jeatheak** [comment]
This card is made by homeassistant. i cannot change or add something in the layout.
But there is an extra service for the horizontal swing.
You can add it to your dashboard.

![afbeelding](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/50164603/de0bdb82-6a73-4e99-a067-a54c7fcd701b)
