### ISSUE TITLE
Temperature sometimes suddenly changed to 33 degrees celsius while it was set to 23 degrees.

### ISSUE THREAD

**Issue by asonnema** [jeatheak/Mitsubishi-WF-RAC-Integration#109]
randomly while i have my temperature set to 23 degrees celcius it changes it to 33 degrees celcius.
This happen to all 4 of my mitsubishi heavy industries airco's

**Comment by theNailz** [comment]
Same here! I haven't been able to figure out what caused this, but I'm seeing the same thing multiple times a day, not per se from 23, but always to 33.

**Comment by jeatheak** [comment]
duplicated issue see #54
