### ISSUE TITLE
async_forward_entry_setup becomes deprecated in HA 2025.6

### ISSUE THREAD

**Issue by Underlyingglitch** [jeatheak/Mitsubishi-WF-RAC-Integration#116]
Detected that custom integration 'mitsubishi_wf_rac' calls async_forward_entry_setup for integration, mitsubishi_wf_rac with title: Airco and entry_id: 58cb088325920a1a9966619bdd17bd18, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/mitsubishi_wf_rac/__init__.py, line 55: hass.async_create_task(, please create a bug report at https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/issues

**Comment by mmaarrkk02** [comment]
This issue was fixed in version 2024.7. Please update the installed package to the latest version.
