### ISSUE TITLE
Cannot add Aircon to HA

### ISSUE THREAD

**Issue by borislavwalltopia** [jeatheak/Mitsubishi-WF-RAC-Integration#119]
Hi guys,
I'm getting the following error when trying to add the unit to Home assistant:

Could not connect with the Airco: HTTPConnectionPool(host='192.168.0.14', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f52c980>: Failed to establish a new connection: [Errno 111] Connection refused'))

Any ideas?

**Comment by jeatheak** [comment]
Hi,

Did the integration discover the Airco by itself? Or did you input the IP address yourself?

It seems that it cannot find the Airco and therefore cannot connect.

Is it also connected via the smart-m air app?

**Comment by borislavwalltopia** [comment]
As soon as I try to add the integration I'm getting this screen:
![image](https://github.com/user-attachments/assets/1b1c0788-718e-4cae-96e0-5953d799ee9b)

I'm using airconwithme app and it's connected and working

**Comment by borislavwalltopia** [comment]
Arghh sorry, just saw my unit has the old wifi module... please close the topic
