### ISSUE TITLE
add swing left/right service

### ISSUE THREAD

**Issue by jeatheak** [jeatheak/Mitsubishi-WF-RAC-Integration#12]
Currently it is not possible to set the left/right swing/fan position.
This is due to the climate entity limitations.

Therfore it would be nice to set it trough a service and mayby a input slider or something alike.

**Comment by jeatheak** [comment]
There is already a option to enable 3D Auto:

![image](https://user-images.githubusercontent.com/50164603/187677838-e9b8686e-c57d-4f8b-adf7-c467679ae87a.png)

**Comment by SanderKo85** [comment]
Would be great to control Left/Right fan position (blowing direction). Not all units have this feature, but the units I have do.
The 'Smart M-Air app' gives me the following options;

![20221206_102332](https://user-images.githubusercontent.com/119807149/205872019-eb56b2af-0e10-47e8-8aaf-4a61670a2368.gif)
