### ISSUE TITLE
Add reload integration to integration context menu. 

### ISSUE THREAD

**Issue by Midifreakz** [jeatheak/Mitsubishi-WF-RAC-Integration#121]
Is there a special reason why there is no 'reload button at a integration entry? 
Not having this control sometimes makes it difficult to troubleshoot HASS stuff. 

<img width="870" alt="Screenshot 2024-10-18 at 19 43 35" src="https://github.com/user-attachments/assets/21dd105e-087d-4319-9ae1-73a9c410b496">

**Comment by jeatheak** [comment]
Which version are you running? Because it would be there.

See screenshot.

![image](https://github.com/user-attachments/assets/9f896de4-52f5-4c60-89ea-8b4b5ac811d7)

**Comment by Midifreakz** [comment]
Hi Jeatheak, 

Thanks for the reply. 
I got it popping up by re-installing the integration.
