### ISSUE TITLE
Config flow could not be loaded (invalid handler specified)

### ISSUE THREAD

**Issue by PaulvdL** [jeatheak/Mitsubishi-WF-RAC-Integration#29]
Hi,
I tried to install the integration into Home Assistant using HACS.
I am able to download the custom repository with HACS.
But when I want to add the integration, I receive the following error message:

"Config flow could not be loaded (message: invalid handler specified)"

What could be the reason?

**Comment by PaulvdL** [comment]
I have solved the problem

**Comment by jeatheak** [comment]
Ok,
Glad to hear.
What did the trick?

**Comment by PaulvdL** [comment]
Hi,

 

I have removed the directory and redownloaded and installed the integration.

 

Regards,

 

Paul van der Lelij

 

 

Van: jeatheak ***@***.***> 
Verzonden: vrijdag 18 november 2022 08:48
Aan: jeatheak/Mitsubishi-WF-RAC-Integration ***@***.***>
CC: PaulvdL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jeatheak/Mitsubishi-WF-RAC-Integration] Config flow could not be loaded (invalid handler specified) (Issue #29)

 

Ok,
Glad to hear.
What did the trick?

**Comment by jeatheak** [comment]
Seemed to be solved by the user.
