### ISSUE TITLE
Can't connect with airco anymore

### ISSUE THREAD

**Issue by Legendhidde** [jeatheak/Mitsubishi-WF-RAC-Integration#31]
Hi there, I'm completely new to everything so I don't know what I should do. Suddenly one of my aircons using this integration just gave me "Unavailable" on a random day. When I try to add it again it gives me this error message:

HTTPConnectionPool(host='192.168.50.18', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f503dc30cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

I am using version 0.2.

**Comment by Legendhidde** [comment]
Can't seem to add a bug label, apologies

**Comment by Legendhidde** [comment]
[home-assistant_mitsubishi-wf-rac_2022-12-17T10-48-43.872Z.log](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/files/10251520/home-assistant_mitsubishi-wf-rac_2022-12-17T10-48-43.872Z.log)
Here is one of the log files.

**Comment by Legendhidde** [comment]
Forgot to mention that I’m already on 0.2.0, so the fix had no effect.

**Comment by Legendhidde** [comment]
Ah I’ve read the other issues and realised I’m not alone with this and that you don’t have a lot of time to look into it. Apologies, I’d love to help where possible because it’s getting impossible to trust my automations. Could try contacting someone from Mitsubishi to ask what the error message means.

**Comment by Legendhidde** [comment]
Even a reset hasn’t fixed this issue, like it has for other people. I even set the airco to only be controlled locally, hoping that this would fix it. Is this also what other people have set? I did have it set to out-of-house control, might try completely deleting the app once.

**Comment by Legendhidde** [comment]
It seems to always happen when trying to update the airco values.

Error: something went wrong updating the airco [Airco Office] values
Error: something went wrong updating the airco [Airco Living Room] values
Could not send airco data

Maybe the update calls need a time out too?

**Comment by jeatheak** [comment]
> Ah I’ve read the other issues and realised I’m not alone with this and that you don’t have a lot of time to look into it. Apologies, I’d love to help where possible because it’s getting impossible to trust my automations. Could try contacting someone from Mitsubishi to ask what the error message means.

Hi, apologies for my late reply, but contacting Mitsubishi will not help and be a good option because we reverse engineered the app and use the api in a way we "think" is a good practice. Furthermore is the error message generated by the code from library used.

**Comment by jeatheak** [comment]
> Even a reset hasn’t fixed this issue, like it has for other people. I even set the airco to only be controlled locally, hoping that this would fix it. Is this also what other people have set? I did have it set to out-of-house control, might try completely deleting the app once.

It should also work in not local mode. there is no difference in that connection there.

**Comment by jeatheak** [comment]
> It seems to always happen when trying to update the airco values.
> 
> Error: something went wrong updating the airco [Airco Office] values Error: something went wrong updating the airco [Airco Living Room] values Could not send airco data
> 
> Maybe the update calls need a time out too?

It looks like the connection to the airco failed. what do you see in the app if you go to the airco->settings->users (at the bottom) I think. I cannot connect to the app at the moment because I'm not at home.

**Comment by Legendhidde** [comment]
> > It seems to always happen when trying to update the airco values.
> > Error: something went wrong updating the airco [Airco Office] values Error: something went wrong updating the airco [Airco Living Room] values Could not send airco data
> > Maybe the update calls need a time out too?
> 
> It looks like the connection to the airco failed. what do you see in the app if you go to the airco->settings->users (at the bottom) I think. I cannot connect to the app at the moment because I'm not at home.

Should I check that setting during one of the connection problems? Right now it’s all working again and it says “Number of Smartphones: 2” but I don’t quite know how to reduce that number. In home assistant it shows as having “2 accounts”

During one of the errno 111 sessions I don’t seem to be able to connect via the Mitsubishi app either, it doesn’t show any information for the affected unit.

No worries about the late reply by the way, I’m already very grateful you can help me.

**Comment by Legendhidde** [comment]
The airco’s are indeed connected right now, I’ve updated to the main branch and restarted, I’ll keep you updated on whether I see an error, happens once or twice a day.

**Comment by Legendhidde** [comment]
After switching to the main branch, so far so good! Running 8 hours so far without any more issues, empty log files 👍 Will keep you updated if anything pops up

**Comment by Legendhidde** [comment]
Shouldn’t have jinxed it, error happened once more

**Comment by Legendhidde** [comment]
Turned off “Polling for updates” in the integration settings for both units on top of switching to the main branch and I haven’t had this error in 2 days now.

**Comment by Legendhidde** [comment]
A week later, polling for updates off and running main branch and it’s been flawless. No problems anymore.
