### ISSUE TITLE
eco mode

### ISSUE THREAD

**Issue by R8tro** [jeatheak/Mitsubishi-WF-RAC-Integration#36]
would it be possible to add eco mode to the intergration?

**Comment by jeatheak** [comment]
Hi,

Unfortunately not at the moment. because in the app this option is not present and therefore we don't know how to send the encrypted value to the Airco.

**Comment by seidler2547** [comment]
According to the manual, all that ECO mode does is:

> The unit operates 1.5 °C higher than the setting temperature during cooling or 2.5 °C lower than that during heating.

So no real function that needs to be implemented. This should also answer #66
