### ISSUE TITLE
After update no option for right left swing

### ISSUE THREAD

**Issue by mariusnauj** [jeatheak/Mitsubishi-WF-RAC-Integration#39]
Hello,

I updated integration. FIrst deleted deviece, then deleted integration from HACS, rebotted HA. Install again new version, rewbooted HA. Added integration, but no option for swing left/right.

![image](https://user-images.githubusercontent.com/90972238/215054960-a2894c8f-75dd-4378-99a0-8e21db9c0db6.png)

**Comment by jeatheak** [comment]
Hi @mariusnauj,

It is not possible to add this option to the climate card/entity.
Therefore @bjorne did add it as a new service to the services.

See picture below:

![image](https://user-images.githubusercontent.com/50164603/215079508-7ebc6440-850c-4f9a-a9b5-4910f76b146a.png)

You can call this manually, with a button on UI or automation.

**Comment by jeatheak** [comment]
@mariusnauj you found it?

**Comment by mariusnauj** [comment]
@jeatheak yes I found it. Thank you
