### ISSUE TITLE
Feature request: add horizontal swing support

### ISSUE THREAD

**Issue by niro1987** [jeatheak/Mitsubishi-WF-RAC-Integration#49]
With the remote and the app, I can set the horizontal swing to [auto, left-left, left-center, center-center, center-right, right-right, left-right, right-left]. I would like to be able to do the same in Home Assistant.

**Comment by niro1987** [comment]
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/7474625/88f5180f-241f-4f42-808f-dd29e66a9cc9)

**Comment by niro1987** [comment]
https://github.com/home-assistant/architecture/discussions/553

I see that the code alrady supports horizontal swing modes but the HA climate integration does not. Would it be veasable to add a sensor with the active horzintal swing mode so that an automation could be created to support this feature as long as the HA climate integration is updated?

**Comment by DickAppel** [comment]
I have this integration active from when it was launched. I am awaiting the extended swing implementation from the same time. Hopefully someone will bother soon. I am sure many would appreciate it.

**Comment by jeatheak** [comment]
Hey @niro1987 @DickAppel I added a select component that you can add to dashboard and/or automation. You can also read the current horizontal swing directioon from its state. Hopefully it is what you needed. Let me now id something is missing.

**Comment by niro1987** [comment]
Love it! #closed
