### ISSUE TITLE
Bump aenum requirement from aenum==3.1.11 to aenum>=3.1.11 or aenum==3.1.12

### ISSUE THREAD

**Issue by Veda82** [jeatheak/Mitsubishi-WF-RAC-Integration#50]
I'm using Home Assistant in a docker environment with this image:

https://hub.docker.com/r/linuxserver/homeassistant

In this image, aenum has been updated to version 3.1.12; the integration requires version 3.1.11.

Unfortunately, due to some permission issues, Home Assistant cannot downgrade the package in this docker image, see:

https://github.com/linuxserver/docker-homeassistant/issues/74

There is a solution using a docker mod:

https://github.com/linuxserver/docker-mods/tree/universal-package-install

but it would be easier /  neater if the integration requirement could be changed in:

aenum>=3.1.11

or

aenum==3.1.12

**Comment by tismij** [comment]
have the same issue, how did you fix this until req changed ?

**Comment by Veda82** [comment]
@tismij if you're using the same Docker image, you can use:

https://github.com/linuxserver/docker-mods

Basically, you should add these environment variables to your container configuration:

DOCKER_MODS=linuxserver/mods:universal-package-install
INSTALL_PIP_PACKAGES=aenum==3.1.11

**Comment by tismij** [comment]
noticed in manifest.json it says:  "requirements": ["aenum==3.1.11"]
When I have more time will try changing in here and seeing if that is enough.

**Comment by jeatheak** [comment]
Hey @Veda82 @tismij  I changed the requirements to >= 3.1.11 hopefully it will fi the issue for you.

**Comment by Veda82** [comment]
Great! I will test and let you know!

**Comment by Veda82** [comment]
Just tested the update, everything seems fine to me...

Thanks for the support!
