### ISSUE TITLE
Fix missing icons for integration

### ISSUE THREAD

**Issue by jeatheak** [jeatheak/Mitsubishi-WF-RAC-Integration#52]
Fix the missing Icons in the Device and integration page.

![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/50164603/712213b1-5694-4278-83aa-9f555c567a70)

**Comment by hmmbob** [comment]
Issue can be closed, icons are active

![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/33529490/b44a3df0-d8b8-41d3-bbbf-eb9d5bc7ae41)
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/33529490/551a321e-9679-4d32-bdce-ba1c4ad55634)
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/33529490/bdbd0d21-aca3-4b27-803d-2b994d5e38f5)

**Comment by FoUStep** [comment]
Hmmm can they be made transparant? Looks better on dark themes in HA.

**Comment by hmmbob** [comment]
I just reused icons found online, but it's open source so go ahead and change by creating a pull request in the brands repository of home assistant:

https://github.com/home-assistant/brands/

**Comment by jeatheak** [comment]
@hmmbob Thank you for adding them 😄
