### ISSUE TITLE
Self Clean options

### ISSUE THREAD

**Issue by FoUStep** [jeatheak/Mitsubishi-WF-RAC-Integration#55]
Feature request, the module is missing the self clean option. Could this please be added?

**Comment by mcheijink** [comment]
As far as I know, this is not part of the interface that we implemented in 2022. Can you share a bit on your airco model?

**Comment by FoUStep** [comment]
Ah yes, sorry. The MHI SRK35ZS-W. And my bad, this is not in the web interface of the Smart M-Air app. I will close this.
