### ISSUE TITLE
Feature request: Add hvac_mode information

### ISSUE THREAD

**Issue by c0mplex1** [jeatheak/Mitsubishi-WF-RAC-Integration#64]
In addition to fan_mode and swing_mode, also add hvac_mode information, so that the user can see what the actual setting of the air conditioning is, even when it is off.

Thank you.

**Comment by sean-2024** [comment]
Similar feature request....

The horizontal swing is a separate entity, it would be great if the vertical mode could be too.

Thank you.

**Comment by c0mplex1** [comment]
Any news on this?
![afbeelding](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/81088928/dee3d131-b16c-43b6-a15e-75f80efa7594)

**Comment by c0mplex1** [comment]
Bump!

**Comment by c0mplex1** [comment]
No one?
Not just a simple response to my request?

**Comment by jeatheak** [comment]
At the moment I am very busy with other stuff. If I have time I will look into this. 

But I cannot guarantee that it will be implemented in a short time.

For my info: why do you want it?
Because for me personally it does not matter what setting is active. (When off).
I just set it to the state I want it.

**Comment by c0mplex1** [comment]
Thank you for your response. I really appreciate this.

You can pull all kinds of information from the integration, except HVAC-mode information.
I want to use this information to automate my aircons.
I know the info is available as the 'state' of the AC-units, but for me, it makes more sens if you can use the attribute 'hvac_mode'. Like the same way you can get the status of the fan and swing mode.
That's why my feature request.
