### ISSUE TITLE
Climate: Add fan speed adjustment trough automation

### ISSUE THREAD

**Issue by nickdorrestein** [jeatheak/Mitsubishi-WF-RAC-Integration#68]
I would like to add an automation to turn the airco on during night times but on a low fan speed to reduce noise. To be able to do this the fan speed needs to be adjustable trough an automation.

**Comment by mr-romeijn** [comment]
Was searching through the issues to figure out how to do this. You can actually call the service to set fan speed within an animation. Though the value is a manual text input. I was trying to figure out what inputs are used or need to be used to set the wanted fan speed.

**Comment by LesNewell** [comment]
Take a look at the scheduler custom card. [https://community.home-assistant.io/t/scheduler-card-custom-component/217458](url)
It works very well with this integration and will do exactly what you want. Among other things I use it to run the fan at minimum speed at night.
