### ISSUE TITLE
Unit turns off due to call to set_temperature shortly after turning on

### ISSUE THREAD

**Issue by RudolfRendier** [jeatheak/Mitsubishi-WF-RAC-Integration#70]
I'm trying to automate my units with:
* Home Assistant
* Schedy
* This awesome integration

When Schedy activates a schedule, it turns on heating and sets the temperature in short succession.
Unfortunately the result is that devices switches on and immediately off again.

This is what is shown in the log:
![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/490658/cf1fe388-ead2-4762-af3b-bfaf08fec98f)
(Supervisor because Schedy runs in AppDaemon add-on)

What's even worse is that Schedy sees this as a manual change by the user and will back off for a configurable amount of time.
The built-in resend mechanism in Schedy doesn't trigger.

I checked the service calls by schedy, via HA debug tools, and for the call to set_temperature there is no hvac_mode argument.
So it should leave it at 'Heating' as set by the previous service call.

Could it be this method is called with incorrect arguments?
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/07c0f9f0eb40c5453ced12e620b121bcd17b84f3/custom_components/mitsubishi_wf_rac/climate.py#L105

**Comment by RudolfRendier** [comment]
The history belows shows how Schedy 'fixes' the issue after one hour, because the back off timer expires.
Then it only set's the mode, without the temperature and it stays on:

![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/490658/0d5b9290-74b9-405b-8e8d-c7e221c3bbe2)

**Comment by dizzydnallov** [comment]
Hi @RudolfRendier 

I'm having a similar issue, but I'm unsure if it is related; what is the "PR 61" you found?

**Comment by jeatheak** [comment]
PR #61 is merged in v0.5.0
