### ISSUE TITLE
No issue but question

### ISSUE THREAD

**Issue by arazok** [jeatheak/Mitsubishi-WF-RAC-Integration#76]
Hi,
I like this adapter (from reading), but I am using ioBroker, not HA.
For ioBroker there is also this kind of MHI air conditioner adapter using WF-RAC, and it is working.
BUT: When you use the aircon with ioBroker plugin, you are not able to use it with the Smart M-Air App.
There is always an error (in the App) saying: used by another account.

So, do you have the same problem here with this adapter for HA and the Smart M-Air App ?
And if not, how get you rid of this problem ?

Thanks for any info.
cheers,
Arazok

**Comment by sean-2024** [comment]
I see the 'used by another account' crop up from time to time in the Smart M-Air App. So I think the problem may be similar. 

I rarely open up the Smart M-Air App though and generally just manage via HA.

**Comment by jeatheak** [comment]
I noticed it happen when homeassistant is doing a lot of calls. So it seems it cannot handle 2 connected deviecs at once.
Is the ioBroker polling or sending commands a lot?
