### ISSUE TITLE
Can't add AC after reinstalling integration

### ISSUE THREAD

**Issue by Megalos** [jeatheak/Mitsubishi-WF-RAC-Integration#81]
The ACs didn't connect anymore to HA, so I decided to remove and redownload the integration. Now, when I try to add one of my 4 ACs, I get the message: 

`Could not connect with the Airco: HTTPConnectionPool(host='192.168.189.15', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff6c1505290>, 'Connection to 192.168.189.15 timed out. (connect timeout=30)'))`

In the Smart M-Air app, when I click one of the ACs, choose 'Options', the 'Number of smartphones' is 4. Not sure if that's an issue. The firmware of the ACs is 010/131, and I'm using the v0.5.0 of the integration. In the Smart M-Air app, I'm using the 'Remote operation mode', and all 4 ACs are in my Guest wifi network. HA is on the main wifi network. From the Smart M-Air app, I can control the ACs fine (3 out of 4, the 4th one I didn't manage to properly connect from the app).

Do anyone have any ideas how to add the ACs in HA?

![ha_smart_m_air_error](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/1153410/1b080d71-963d-4efb-8776-2ca635dbc1b3)

![Screenshot_20240204-171435](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/1153410/7c7ed18e-ed94-4e08-b349-07122126fd26)

**Comment by jeatheak** [comment]
Hi,

It is indeed a problem that the app is saying it has 4 connected devices.
Because the AC can have up to 4 connections.

Unfortunately it means that is has 4 connections but some have not properly deregistered.

To solve this you need to deregistered 1 or more devices or reset the wifi module in the AC and register the remote devices again (app and home assist)

**Comment by Megalos** [comment]
Thanks jeatheak. How can I properly deregister a device?

**Comment by 290989** [comment]
> Hi,
> 
> It is indeed a problem that the app is saying it has 4 connected devices. Because the AC can have up to 4 connections.
> 
> Unfortunately it means that is has 4 connections but some have not properly deregistered.
> 
> To solve this you need to deregistered 1 or more devices or reset the wifi module in the AC and register the remote devices again (app and home assist)

Did I understand correctly that I can connect a maximum of 4 devices? What can I do if I have more than 4 indoor units?

**Comment by jeatheak** [comment]
> > Hi,
> > 
> > It is indeed a problem that the app is saying it has 4 connected devices. Because the AC can have up to 4 connections.
> > 
> > Unfortunately it means that is has 4 connections but some have not properly deregistered.
> > 
> > To solve this you need to deregistered 1 or more devices or reset the wifi module in the AC and register the remote devices again (app and home assist)
> 
> Did I understand correctly that I can connect a maximum of 4 devices? What can I do if I have more than 4 indoor units?

No not entirely. It means that you can have up to 4 controller devices such as a mobile phone or home assist connections. 

The 4 connected devices are unique per AC unit. So when you add a unit to the app it will occupy 1 space in the AC unit and the unit has space for max 4 devices.

**Comment by jeatheak** [comment]
> Thanks jeatheak. How can I properly deregister a device?

Normally this is done automatically by the mobile app (if you remove an AC unit) or by the home assistant integration if you remove the unit or integration. 

Of course it is possible that something went wrong in the integration and the AC unit still has a registered instance.

Unfortunately to remove/reset this. you need to reset the wifi module in the AC unit. It has a reset button on the wifi module. (Press and hold it as far as I know)

After that you need to re-add the unit to home assist and your mobile app.

**Comment by 290989** [comment]
> > > Hi,
> > > It is indeed a problem that the app is saying it has 4 connected devices. Because the AC can have up to 4 connections.
> > > Unfortunately it means that is has 4 connections but some have not properly deregistered.
> > > To solve this you need to deregistered 1 or more devices or reset the wifi module in the AC and register the remote devices again (app and home assist)
> > 
> > 
> > Did I understand correctly that I can connect a maximum of 4 devices? What can I do if I have more than 4 indoor units?
> 
> No not entirely. It means that you can have up to 4 controller devices such as a mobile phone or home assist connections.
> 
> The 4 connected devices are unique per AC unit. So when you add a unit to the app it will occupy 1 space in the AC unit and the unit has space for max 4 devices.

Ok, thank you for your fast feedback & thank you for your work. :)

**Comment by Megalos** [comment]
Thanks jeatheak, I reset the wifi module, and now it correctly adds to HA and the app again. But only when I connect the ACs to the main wifi network, and not to the Guest network. Is that intended behavior? The guest network uses a different IP range (192.169.189.xxx instead of 192.168.178.xxx). HA is on the main wifi network. Is adding to HA supposed to work when the ACs and HA are on different IP ranges?

**Comment by jeatheak** [comment]
> Thanks jeatheak, I reset the wifi module, and now it correctly adds to HA and the app again. But only when I connect the ACs to the main wifi network, and not to the Guest network. Is that intended behavior? The guest network uses a different IP range (192.169.189.xxx instead of 192.168.178.xxx). HA is on the main wifi network. Is adding to HA supposed to work when the ACs and HA are on different IP ranges?

It depends how the guest network is configured. If it is a normal guest network it usually is isolated and is indeed on a different subnet and cannot route between subnets. 

If your guest network is manually configured with vlans and the correct firewall rules it is possible to reach different subnets (I have that) but it is quite an advanced configuration and your router should support this.

So to conclude: usually it is not possible to add it from a different (guest) network.

**Comment by jeatheak** [comment]
@Megalos is it ok for me to close this issue or do you have more questions?

**Comment by Megalos** [comment]
Hi jeatheak, thanks. I reset the wifi module, and now it's working when I take it out of the guest network, and in the main network. For now, this is fine. Thanks for the detailed answers and quick responses! The issue can be closed.
