### ISSUE TITLE
Add Pulldowns from the popup CARD to default CARD

### ISSUE THREAD

**Issue by agile-scrum-master** [jeatheak/Mitsubishi-WF-RAC-Integration#83]
First I want to thank the deveoper(s) for this plugin, thank you!!

Request:
In the popup CARD there are 3 beautifull buttons/pulldowns. I would like to have them in the default CARD. 
And a powerbutton in the front. Then I have everyting to control the airco from the CARD

![airco](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/133636509/71db60e3-2dd0-4eeb-9974-5a81458b7f69)

Must be simple because the pulldowns exist?
More people would like to have this feature?

**Comment by sean-2024** [comment]
I would like to see this sort of feature too.

At the moment I have this not too elegant arrangement of things stuck together, so it's all controllable via one screen. 

![Screenshot 2024-02-19 at 14 12 01](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/156532753/8d5784d2-71f3-46ae-9a5c-d641dbebb175)

**Comment by jeatheak** [comment]
the card is generated by Homeassistant I did not create it and cannot edit it.
