### ISSUE TITLE
No energy monitoring

### ISSUE THREAD

**Issue by xsibit666** [jeatheak/Mitsubishi-WF-RAC-Integration#86]
Hello everyone,

HA version:
Core: 2024.2.2
Supervisor: 2024.01.1
Operating system: 11.5
Frontend: 20240207.1

Mitsubishi WF-RAC Integration Integration Version: 2024.2.1, v0.5.0, v0.4.0

My next problem with the integration is that it doesn't provide me with any values ​​about power consumption.
Everything else works great.

**Comment by jeatheak** [comment]
Are the sensors added? because if they are not added the AC unit does not provide it or we deon't know how to parse it.
I have 1 AC that provides it and 1 that does not.

Is it shown in the app?

**Comment by jeatheak** [comment]
Ok, then unfortunately it is not possible to read it. That's why it is not showing up in Home assist.

**Comment by xsibit666** [comment]
This means that the air conditioning units do not have this function

**Comment by jeatheak** [comment]
To my knowledge yes. 
But I'm not entirely sure of course.

It's just that I don't know how to read it as long as it is not in the app.

I use the app to see how to decode the messages to read and send to the AC

**Comment by jeatheak** [comment]
I used the app to reverse engineer the encrypted communication protocol that they are using. 

So if the app has a command I can reverse engineer or capture it. 

Without the app it is really difficult to know what to send and receive.

**Comment by jeatheak** [comment]
I used the app to reverse engineer the encrypted communication protocol that they are using. 

So if the app has a command I can reverse engineer or capture it. 

Without the app it is really difficult to know what to send and receive.

So the home assistant is not using the app of course.
