### ISSUE TITLE
After updating from 2024.2 to 2024.2.1 it doesnt work anymore

### ISSUE THREAD

**Issue by asonnema** [jeatheak/Mitsubishi-WF-RAC-Integration#88]
After updating from 2024.2 to 2024.2.1 it doesnt work anymore (see logs)

[home-assistant_2024-02-22T08-35-42.771Z.log](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/files/14371070/home-assistant_2024-02-22T08-35-42.771Z.log)

**Comment by jeatheak** [comment]
Wat version of the core are you running. It is only compatible with 2024.2 and up.

**Comment by asonnema** [comment]
You we're right, my core version was 2042.1.
I've updated it and its working now.
Thanks!
