### ISSUE TITLE
Re-register Unit - Reading states and values but unable to issue commands

### ISSUE THREAD

**Issue by robyholmes** [jeatheak/Mitsubishi-WF-RAC-Integration#93]
Hi,
One of our wall units seemed to drop off both home assistant and the M Air app. I could ping it but not read or control it. So I reset the wireless module and got it connected back. 

The units IP hasn't changed and home assistant shows it as online. Temperatures and status etc are updating but any changes I make to temperature or mode in HA are not applied to the unit. Almost like it's in read only mode. If I change it by the M Air app it works, and HA updates after a while to show this.

Do I need to remove the device and re-add it. Or can I get it to register? I'm guessing operator ID has changed which is causing this?

I'm concerned if I remove it, I'll have to reset up scenes, helpers, cards etc. So trying to save doing this. Especially if it's going to happen in the future again.

Thanks,
Rob Holmes

**Comment by robyholmes** [comment]
Removed and re-added the device and all entities remained the same. Scenes had to be checked and set again, but the device was present.

**Comment by jeatheak** [comment]
glad to hear that it worked. If you reset the wireless module you indeed need to add them again. and if as long as you give them the same name as before (after deleting the old one) it should be ok.
