### ISSUE TITLE
Detected that custom integration 'mitsubishi_wf_rac' calls `async_add_job`, which is deprecated

### ISSUE THREAD

**Issue by hmmbob** [jeatheak/Mitsubishi-WF-RAC-Integration#94]
Seeing this error on 2024.4.3:

> 2024-04-19 19:04:41.236 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'mitsubishi_wf_rac' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/mitsubishi_wf_rac/climate.py, line 187: self._hass.async_add_job(self._set_airco_after_delay), please create a bug report at https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/issues

**Comment by c0mplex1** [comment]
I have the same error message.
