### ISSUE TITLE
Could not connect with Airco

### ISSUE THREAD

**Issue by 49Penrose** [jeatheak/Mitsubishi-WF-RAC-Integration#97]
Hi there, very new HA user here, trying to integrate my Mitsubishi A/C (controlled via Wi-Fi Control app) into HA. Got HACS working and download this repo, when trying to add integration I get following error message

Could not connect with the Airco: HTTPConnectionPool(host='192.168.0.142', port=51443): Max retries exceeded with url: /beaver/command/getDeviceInfo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8a976150>, 'Connection to 192.168.0.142 timed out. (connect timeout=30)'))

Please help this would be a fantastic addition to my HA, as these AC cant be controlled via sensibo

**Comment by svetoslavpopov93** [comment]
I am having the same issue here, but i am not able to find a sllution...

**Comment by sean-2024** [comment]
I think the "Wi-Fi Control" is for controlling Mitsubishi Electric air conditioning devices. 

This integration is only for Mitsubishi Heavy Industries equipment, completely separate companies confusingly.

**Comment by jeatheak** [comment]
Yeah indeed, I think it is a different communication protocol the Wifi app uses.

This integration works with the WF-RAC wifi module that work with the "Smart M-Air" app.
